### PR TITLE
WEBVTT - Fix WEBVTT missing text alignment tags from output

### PR DESCRIPTION
**Pull request by vish91**
Fixes: #925 
Fixes a bug where the package was failing to add the right text Alignment tag on the segmented vtt output generated for both DASH and HLS. 

To reproduce from master branch try running on test input
```
$ packager 'in=SampleVideo_1280x720_30mb.mp4,stream=video,segment_template=/tmp/SampleVideo_1280x720_30mb_hls/seg_$Number$.ts,iframe_playlist_name=SampleVideo_1280/stream_iframe.m3u8,playlist_name=SampleVideo1280x720/stream.m3u8' \
'in=SampleVideo_1280x720_30mb.mp4,stream=audio,segment_template=/tmp/Sample_video_1280x720_hls/seg_$Number$.aac,lang=en,hls_name=English' 'in=1835844163863-web.vtt,stream=text,language=en,segment_template=/tmp/1835844163863-ttml-hls/seg_$Number$.vtt,hls_group_id=cbsi_vtt,hls_name=English' \
--segment_duration 6 --hls_master_playlist_output /tmp/SampleVideo_1280x720_30mb_hls/master.m3u8

[0324/172546:INFO:demuxer.cc(89)] Demuxer::Run() on file '1835844163863-web.vtt'.
[0324/172546:INFO:demuxer.cc(155)] Initialize Demuxer for file '1835844163863-web.vtt'.
[0324/172546:INFO:demuxer.cc(89)] Demuxer::Run() on file 'SampleVideo_1280x720_30mb.mp4'.
[0324/172546:INFO:demuxer.cc(155)] Initialize Demuxer for file 'SampleVideo_1280x720_30mb.mp4'.
[0324/172549:INFO:mp4_media_parser.cc(345)] Ignore unused 'mdat' box - this could be as a result of extra not usable 'mdat' or 'mdat' associated with unrecognized track.
Packaging completed successfully.
$ cat /tmp/1835844163863-ttml-hls/seg_1.vtt
WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:9000

00:00:03.670 --> 00:00:04.462 line:85% position:28% size:35%
&gt;&gt; Devon: Hey.

00:00:04.546 --> 00:00:05.088 line:79% position:10% size:73% align:start
&gt;&gt; Amanda: Naya backed out on
our meeting.

00:00:05.171 --> 00:00:07.424 line:85% position:43% size:65%
&gt;&gt; Devon: Did she say why?
```

with this fix 

```
$packager 'in=SampleVideo_1280x720_30mb.mp4,stream=video,segment_template=/tmp/SampleVideo_1280x720_30mb_hls/seg_$Number$.ts,iframe_playlist_name=SampleVideo_1280/stream_iframe.m3u8,playlist_name=SampleVideo1280x720/stream.m3u8'\
'in=SampleVideo_1280x720_30mb.mp4,stream=audio,segment_template=/tmp/Sample_video_1280x720_hls/seg_$Number$.aac,lang=en,hls_name=English' 'in=1835844163863-web.vtt,stream=text,language=en,segment_template=/tmp/1835844163863-ttml-hls/seg_$Number$.vtt,hls_group_id=cbsi_vtt,hls_name=English' \
--segment_duration 6 --hls_master_playlist_output /tmp/SampleVideo_1280x720_30mb_hls/master.m3u8
[0324/172855:INFO:demuxer.cc(89)] Demuxer::Run() on file '1835844163863-web.vtt'.
[0324/172855:INFO:demuxer.cc(155)] Initialize Demuxer for file '1835844163863-web.vtt'.
[0324/172855:INFO:demuxer.cc(89)] Demuxer::Run() on file 'SampleVideo_1280x720_30mb.mp4'.
[0324/172855:INFO:demuxer.cc(155)] Initialize Demuxer for file 'SampleVideo_1280x720_30mb.mp4'.
[0324/172859:INFO:mp4_media_parser.cc(345)] Ignore unused 'mdat' box - this could be as a result of extra not usable 'mdat' or 'mdat' associated with unrecognized track.
Packaging completed successfully.

$ cat /tmp/1835844163863-ttml-hls/seg_1.vtt
WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:9000

00:00:03.670 --> 00:00:04.462 line:85% position:28% size:35% align:center
&gt;&gt; Devon: Hey.

00:00:04.546 --> 00:00:05.088 line:79% position:10% size:73% align:start
&gt;&gt; Amanda: Naya backed out on
our meeting.

00:00:05.171 --> 00:00:07.424 line:85% position:43% size:65% align:center
&gt;&gt; Devon: Did she say why?
```

### CODE REVIEW

**Comment by kqyang** [comment]
@vish91 Can you fix the 4 failed unit-tests reported by AppVeyor? Click the AppVeyor link for details. 

The end to end python tests may need to be updated too.

Let me know if you have questions.

**Comment by vish91** [comment]
@kqyang  have fixed the unit tests, the build errors on the last CI run is unclear to me. Can you please check or help just re-run it one more time.

**Comment by kqyang** [comment]
@vish91 The end to end test artifacts need to be updated too.

You can run `out/Debug/packager_test.py --test_update_golden_files` or  `out/Release/packager_test.py --test_update_golden_files` to update it.

**Comment by vish91** [comment]
@kqyang  I ran that on my local branch. I see a git diff of ~65 additional files all under `packager/third_party/protobuf` does that sound like that's where the  end to end tests are ? or I could just try pushing that change to this PR and see what comes out of it ?

**Comment by kqyang** [comment]
No. The command should update `packager/app/test` directory only. 

Not sure why `packager/third_party/protobuf` was updated. I think you can just revert the changes there.

**Comment by vish91** [comment]
@kqyang  that didn't work either.. running these tests still give me no diff. And it does seem to have completed all the tests
```
 src$ out/Release/packager_test.py --test_update_golden_files
[0421/103217:INFO:demuxer.cc(89)] Demuxer::Run() on file '/Users/vshah0908/work/src/github.com/vish91/shaka-packager/src/out/Release/../../packager/media/test/data/bear-640x360.mp4'.
[0421/103217:INFO:demuxer.cc(155)] Initialize Demuxer for file '/Users/vshah0908/work/src/github.com/vish91/shaka-packager/src/out/Release/../../packager/media/test/data/bear-640x360.mp4'.
[0421/103217:WARNING:avc_decoder_configuration_record.cc(91)] Insufficient bits in bitstream for given AVC profile
[0421/103218:INFO:single_segment_segmenter.cc(111)] Update media header (moov) and rewrite the file to '/var/folders/2t/bs3_t4fj4_gbtr_6h3xwrqdc0000gn/T/tmprhgBW9/bear-640x360-video.mp4'.
[0421/103218:INFO:mp4_muxer.cc(181)] MP4 file '/var/folders/2t/bs3_t4fj4_gbtr_6h3xwrqdc0000gn/T/tmprhgBW9/bear-640x360-video.mp4' finalized.
[0421/103218:INFO:single_segment_segmenter.cc(111)] Update media header (moov) and rewrite the file to '/var/folders/2t/bs3_t4fj4_gbtr_6h3xwrqdc0000gn/T/tmprhgBW9/bear-640x360-audio.mp4'.
[0421/103218:INFO:mp4_muxer.cc(181)] MP4 file '/var/folders/2t/bs3_t4fj4_gbtr_6h3xwrqdc0000gn/T/tmprhgBW9/bear-640x360-audio.mp4' finalized.
[0421/103218:INFO:demuxer.cc(89)] Demuxer::Run() on file '/Users/vshah0908/work/src/github.com/vish91/shaka-packager/src/out/Release/../../packager/media/test/data/not-exist.vtt'.
[0421/103218:INFO:demuxer.cc(155)] Initialize Demuxer for file '/Users/vshah0908/work/src/github.com/vish91/shaka-packager/src/out/Release/../../packager/media/test/data/not-exist.vtt'.
[0421/103218:ERROR:packager_main.cc(550)] Packaging Error: 5 (FILE_FAILURE): Cannot open file for reading /Users/vshah0908/work/src/github.com/vish91/shaka-packager/src/out/Release/../../packager/media/test/data/not-exist.vtt
......
.....
Packaging completed successfully.
.
----------------------------------------------------------------------
Ran 132 tests in 115.648s

OK (skipped=4)
```

**Comment by vish91** [comment]
@kqyang  any thoughts here ?

**Comment by kqyang** [comment]
@vish91 That is weird. I downloaded your patch, and the command worked for me. 

Can you try running the command again to make sure? Perhaps build the targets explicitly again, i.e.

```bash
$ ninja -C out/Release
$ out/Release/packager_test.py --test_update_golden_files
```

**Comment by vish91** [comment]
@kqyang  thanks that worked. had to clean up my workspace and run sync again to this commit ID. I see a diff of 50+ files all vtt's or mp4 segments. 
They are all under `src/packager/test/testdata` so how do we update testdata and check it in for this PR ?

**Comment by kqyang** [comment]
@vish91 Just submit a new commit with all changes in `src/packager/test/testdata`. You can then follow the standard process of updating the PR: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork.

**Comment by vish91** [comment]
@kqyang  the reasons I was asking is as of today in the master branch I don't see the `src` folder and it's files , so are you sure I should check those in with this PR ?

**Comment by kqyang** [comment]
@vish91 Did you follow the instructions in this [link](https://google.github.io/shaka-packager/html/build_instructions.html#get-the-code) to build the code? 

The repo is cloned to `src` directory. All the changes are on the existing files in `packager/test/testdata`.

**Comment by vish91** [comment]
correct, yep I followed that but am confused because running `out/Release/packager_test.py --test_update_golden_files` updates the files under `src/packager/test/testdata` and not in `packager/test/testdata`. So technically I don't have anything to check in yet because from the looks of it, it doesn't look like we check in `src` directory at all.

**Comment by kqyang** [comment]
@vish91 That is weird. Can you share your directory structure?

Anyway, you can copy all the files from `src/packager/app/test/testdata` to `packager/app/test/testdata` and commit the change.

**Comment by vish91** [comment]
```
$ git status
On branch VTTAlign
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gclient
	.gclient_entries
	src/

nothing added to commit but untracked files present (use "git add" to track)
[11:33:30]vshah0908 shaka-packager$ ls
AUTHORS           CONTRIBUTING.md   DEPS              LICENSE           appveyor.yml      docs/             gyp_packager.py*  packager/
CHANGELOG.md      CONTRIBUTORS      Dockerfile        README.md         chromium-LICENSE  foo/              kokoro/           src/
```

^ here's the structure.  

Yeah I can copy files, was just making sure if you have an automated way that I couldn't find anywhere in build steps. Does that work for you if you try and update golden files from this PR ?

**Comment by kqyang** [comment]
Yes, it works for me.

Can you print the value of `SCRIPT_DIR` and `SRC_DIR` in https://github.com/google/shaka-packager/blob/6c8ad30217c286d4eecadc9df12420767d389942/packager/app/test/test_env.py#L24?

**Comment by vish91** [comment]
> Yes, it works for me.
> 
> Can you print the value of `SCRIPT_DIR` and `SRC_DIR` in
> 
> https://github.com/google/shaka-packager/blob/6c8ad30217c286d4eecadc9df12420767d389942/packager/app/test/test_env.py#L24
> 
> ?
```
src$ out/Release/packager_test.py --test_update_golden_files
script dir: /Users/vshah0908/work/src/github.com/vish91/shaka-packager/src/out/Release
src dir:/Users/vshah0908/work/src/github.com/vish91/shaka-packager/src/out/Release/../..
```

**Comment by kqyang** [comment]
Is your repository under `/Users/vshah0908/work/src/github.com/vish91/shaka-packager/` or `/Users/vshah0908/work/src/github.com/vish91/shaka-packager/src`?

**Comment by vish91** [comment]
> Is your repository under `/Users/vshah0908/work/src/github.com/vish91/shaka-packager/` or `/Users/vshah0908/work/src/github.com/vish91/shaka-packager/src`?

Repo is : /Users/vshah0908/work/src/github.com/vish91/shaka-packager/

**Comment by kqyang** [comment]
Do you follow the instructions in https://google.github.io/shaka-packager/html/build_instructions.html#get-the-code as is?

There is no need to clone the repository explicitly.

**Comment by vish91** [comment]
> Did you follow the instructions in https://google.github.io/shaka-packager/html/build_instructions.html#get-the-code as is?
> 
> There is no need to clone the repository explicitly.

I had multiple branches/features so was working from the clone that I had from my fork. Does that make a difference since the repo layout is identical and I followed the other build steps as is ? 

Either way it looks like all the builds are passing now. Let me know once you get some time to review. I also added some notes on #925  so we can talk on that issue if you have any other questions.

**Comment by kqyang** [comment]
@vish91 No, there are no real differences except a minor difference in the end-to-end test artifacts generation :). Feel free to use what you have now if it works for you.

**Pull request merged**
