### PR TITLE
Added 4267, 4819 in each .gyp files for Windows build

### PR DESCRIPTION
**Pull request by Jason239**
Modifying only the common.gyp file does not fix the problem.

So I fixed each modules .gyp file which error occurred.

### CODE REVIEW

**Comment by LeeSangGoo** [comment]
I signed it

**Comment by kqyang** [comment]
@LeeSangGoo Thanks for the pull request!

Can you help try if it works with just the below change:

```diff
diff --git c/packager/common.gypi w/packager/common.gypi
index 6f61d74ec5..de51955881 100644
--- c/packager/common.gypi
+++ w/packager/common.gypi
@@ -42,16 +42,7 @@
             '-Wno-reserved-user-defined-literal',
           ],
         },
-        'conditions': [
-          ['OS == "win"', {
-            'msvs_settings': {
-              'VCCLCompilerTool': {
-                'WarnAsError': 'true',
-                'DisableSpecificWarnings': ['4125']
-              },
-            },
-          }],
-        ],
+        'msvs_disabled_warnings': [ 4125, 4819, ],
       }, {
         # We do not have control over non-shaka code. Disable some warnings to
         # make build pass.
@@ -61,6 +52,7 @@
             '-Wno-unguarded-availability',
           ],
         },
+        'msvs_disabled_warnings': [ 4819, ],
         'conditions': [
           ['clang==0', {
             'cflags': [
```

Thanks for your help!

**Comment by LeeSangGoo** [comment]
Oh I'm sorry, I thought I had already tried it, but I guess I did something wrong.
It succeeds even if I modify only that part.
I will withdraw this pull request.

Thank you very much!

**Comment by LeeSangGoo** [comment]
I would appreciate if you apply that part.

**Comment by kqyang** [comment]
@Jason239 There is nothing wrong in your side :) The patch I gave above is a little bit different to the patch I gave earlier in #419 (I thought the problem was only with third_party builds, but I learned from your patch here that some internal build targets were affected too - we'll dig into it in the future as it should not happen). And yes, we will submit the fix soon. Thanks for your help in verifying the fix!

**Comment by Jason239** [comment]
Ah, I see. That's good :)
So now this issue will be closed.

Thanks !

**Pull request closed without merging**
