### PR TITLE
feat: Cmake port mpd/media_info_proto

### PR DESCRIPTION
**Pull request by zdanek**
Issue #1047 (CMake porting)

### CODE REVIEW

**Review by joeyparrish — APPROVED** [review]

**Comment by joeyparrish** [comment]
@zdanek, @cadubentzen, if there are no objections, I'm ready to merge this.

**Comment by zdanek** [comment]
Waiting for a green light from @cadubentzen

**Comment by cadubentzen** [comment]
All good from my side :+1:

**Comment by zdanek** [comment]
@joeyparrish please, merge

**Pull request merged**
