### PR TITLE
Low latency DASH support 

### PR DESCRIPTION
**Pull request by CaitlinOCallaghan**
# LL-DASH Support
These changes add support for LL-DASH streaming. 
While writing this feature, I have been checking in with @joeyparrish to get feedback along the way. See the original PRs [here](https://github.com/CaitlinOCallaghan/shaka-packager/pulls?q=is%3Apr+is%3Aclosed). 

**NOTE:** LL-HLS support is still in progress, but it's coming. :) 
## Testing
`./chunking_unittest --gtest_filter="ChunkingHandlerTest.LowLatencyDash"`

`./media_event_unittest --gtest_filter="MpdNotifyMuxerListenerTest.LowLatencyDash"`

`./mpd_unittest --gtest_filter="PeriodTest.LowLatencyDashMpdGetXml"`
`./mpd_unittest --gtest_filter="SimpleMpdNotifierTest.NotifyAvailabilityTimeOffset"`
`./mpd_unittest --gtest_filter="SimpleMpdNotifierTest.NotifySegmentDuration"`
`./mpd_unittest --gtest_filter="LowLatencySegmentTest.LowLatencySegmentTemplate"`

Note, packager_test must be run from the main project directory
`./out/Release/packager_test --gtest_filter="PackagerTest.LowLatencyDashEnabledAndUtcTimingNotSet"`
`./out/Release/packager_test --gtest_filter="PackagerTest.LowLatencyDashEnabledAndUtcTimingNotSet"`

## Documentation
image
image

### CODE REVIEW

**Comment by CaitlinOCallaghan** [comment]
Hi, 

I need help with the CLA agreement. I have been able to send PRs to Shaka Streamer, so I know my email `cocallaghan@fb.com` is valid with my company's CLA. 

When I run `git shortlog -e -s -n | grep "Caitlin O'Callaghan"` to check my commits and associated emails I see:
image

Do you reckon the "@users.noreply.github.com" handle from my merges is causing an issue? I peeked in Packager's commit history and saw that other people committed/merged with the "@users.noreply.github.com" handle, and I didn't see issues with their PRs, so I'm not sure this is the problem.

**Comment by kevleyski** [comment]
Thanks Caitlin

**Comment by kqyang** [comment]
@CaitlinOCallaghan Thanks for the PR! 

I checked the CLA, here is what I got:

#### PullRequest Sender

GitHub Login | Email | State
-- | -- | --
CaitlinOCallaghan | 38890251+caitlinocallaghan@users.noreply.github.com | ok

#### Commit Author(s)

GitHub Login | Email | State
-- | -- | --
caitlinocallaghan | cocallaghan@fb.com | ok
caitlinocallaghan | 38890251+CaitlinOCallaghan@users.noreply.github.com | need_author_cla

So yes, the problem is with 38890251+CaitlinOCallaghan@users.noreply.github.com email address. 

There are two options:
- Re-push the commits with the known working email address, i.e. `cocallaghan@fb.com`. I am not sure but `38890251+caitlinocallaghan@users.noreply.github.com` might work too.
- Sign another CLA with email `38890251+CaitlinOCallaghan@users.noreply.github.com`.

**Comment by joeyparrish** [comment]
I need to figure out what is wrong with the PR workflow.  I'll let you know when I've figured that out.  You may need to rebase/merge at that point to pick up the fix.

I'll also try to give this a thorough review soon.  Definitely this week.

**Comment by joeyparrish** [comment]
You should be able to fix the CI issues by rebasing/merging with the master branch now.  Sorry for the inconvenience!

**Review by joeyparrish — APPROVED** [review]
Looks good!

**Comment by kevleyski** [comment]
Thanks Joey

**Comment by CaitlinOCallaghan** [comment]
@joeyparrish No worries! Thank you for the fix and approval!

**Pull request merged**
